import type { CliConfig, CommandConfig } from "../src/types/index.ts";
import { describe, expect, test } from "bun:test";
import {
  generateBashCompletion,
  generateCompletion,
  generateFishCompletion,
  generateZshCompletion,
} from "../src/completions/index.ts";

function createTestConfig(): CliConfig {
  const buildCommand: CommandConfig = {
    name: "build",
    description: "Build the project",
    aliases: ["b"],
    arguments: [],
    options: [
      {
        name: "output",
        short: "o",
        description: "Output directory",
        type: "string",
        required: false,
      },
      {
        name: "watch",
        short: "w",
        description: "Watch mode",
        type: "boolean",
        required: false,
        default: false,
      },
    ],
    subcommands: {},
    hidden: false,
  };

  const serveCommand: CommandConfig = {
    name: "serve",
    description: "Start development server",
    aliases: [],
    arguments: [],
    options: [
      {
        name: "port",
        short: "p",
        description: "Port number",
        type: "number",
        required: false,
        default: 3000,
      },
    ],
    subcommands: {},
    hidden: false,
  };

  const hiddenCommand: CommandConfig = {
    name: "internal",
    description: "Internal command",
    aliases: [],
    arguments: [],
    options: [],
    subcommands: {},
    hidden: true,
  };

  const configSubGet: CommandConfig = {
    name: "get",
    description: "Get config value",
    aliases: [],
    arguments: [],
    options: [
      {
        name: "key",
        short: "k",
        description: "Config key",
        type: "string",
        required: true,
      },
    ],
    subcommands: {},
    hidden: false,
  };

  const configSubSet: CommandConfig = {
    name: "set",
    description: "Set config value",
    aliases: [],
    arguments: [],
    options: [],
    subcommands: {},
    hidden: false,
  };

  const configCommand: CommandConfig = {
    name: "config",
    description: "Manage configuration",
    aliases: ["cfg"],
    arguments: [],
    options: [],
    subcommands: {
      get: configSubGet,
      set: configSubSet,
    },
    hidden: false,
  };

  return {
    name: "test-cli",
    version: "1.0.0",
    description: "Test CLI application",
    commands: {
      build: buildCommand,
      b: buildCommand,
      serve: serveCommand,
      internal: hiddenCommand,
      config: configCommand,
      cfg: configCommand,
    },
    globalOptions: [
      {
        name: "help",
        short: "h",
        description: "Show help",
        type: "boolean",
        required: false,
        default: false,
      },
      {
        name: "version",
        short: "V",
        description: "Show version",
        type: "boolean",
        required: false,
        default: false,
      },
      {
        name: "verbose",
        short: "v",
        description: "Verbose output",
        type: "boolean",
        required: false,
        default: false,
      },
      {
        name: "config",
        short: "c",
        description: "Config file path",
        type: "string",
        required: false,
      },
    ],
  };
}

describe("generateBashCompletion", () => {
  const config = createTestConfig();
  const script = generateBashCompletion(config);

  test("generates valid bash script header", () => {
    expect(script).toContain("#!/usr/bin/env bash");
    expect(script).toContain("# Bash completion for test-cli");
    expect(script).toContain("# Generated by boune");
  });

  test("generates completion function", () => {
    expect(script).toContain("_test_cli_completion()");
  });

  test("includes COMP_WORDS handling", () => {
    expect(script).toContain("COMP_WORDS");
    expect(script).toContain("COMP_CWORD");
    expect(script).toContain("COMPREPLY");
  });

  test("registers completion function", () => {
    expect(script).toContain("complete -F _test_cli_completion test-cli");
  });

  test("includes visible commands", () => {
    expect(script).toContain("build");
    expect(script).toContain("serve");
    expect(script).toContain("config");
  });

  test("excludes hidden commands", () => {
    // Hidden commands shouldn't be in the completions
    const lines = script.split("\n");
    const commandLine = lines.find(
      (l) => l.includes('COMPREPLY=($(compgen -W "') && l.includes("build"),
    );
    if (commandLine) {
      expect(commandLine).not.toContain("internal");
    }
  });

  test("includes command options", () => {
    expect(script).toContain("--output");
    expect(script).toContain("-o");
    expect(script).toContain("--watch");
    expect(script).toContain("--port");
  });

  test("includes global options", () => {
    expect(script).toContain("--help");
    expect(script).toContain("--version");
    expect(script).toContain("--verbose");
    expect(script).toContain("--config");
  });

  test("handles subcommands", () => {
    expect(script).toContain('"config")');
    expect(script).toContain("get");
    expect(script).toContain("set");
  });
});

describe("generateZshCompletion", () => {
  const config = createTestConfig();
  const script = generateZshCompletion(config);

  test("generates valid zsh script header", () => {
    expect(script).toContain("#compdef test-cli");
    expect(script).toContain("# Zsh completion for test-cli");
    expect(script).toContain("# Generated by boune");
  });

  test("generates completion function", () => {
    expect(script).toContain("_test_cli()");
  });

  test("uses _arguments for option parsing", () => {
    expect(script).toContain("_arguments");
  });

  test("includes help and version options", () => {
    expect(script).toContain("--help");
    expect(script).toContain("--version");
  });

  test("includes commands with descriptions", () => {
    expect(script).toContain("build:Build the project");
    expect(script).toContain("serve:Start development server");
    expect(script).toContain("config:Manage configuration");
  });

  test("excludes hidden commands", () => {
    expect(script).not.toContain("internal:Internal command");
  });

  test("includes command options with descriptions", () => {
    expect(script).toContain("--output");
    expect(script).toContain("Output directory");
    expect(script).toContain("--port");
    expect(script).toContain("Port number");
  });

  test("handles subcommands", () => {
    expect(script).toContain("get:Get config value");
    expect(script).toContain("set:Set config value");
  });

  test("ends with function invocation", () => {
    expect(script).toContain('_test_cli "$@"');
  });
});

describe("generateFishCompletion", () => {
  const config = createTestConfig();
  const script = generateFishCompletion(config);

  test("generates valid fish script header", () => {
    expect(script).toContain("# Fish completion for test-cli");
    expect(script).toContain("# Generated by boune");
  });

  test("disables file completion by default", () => {
    expect(script).toContain("complete -c test-cli -f");
  });

  test("generates helper functions", () => {
    expect(script).toContain("function __test_cli_needs_command");
    expect(script).toContain("function __test_cli_using_command");
  });

  test("includes global options", () => {
    expect(script).toContain("complete -c test-cli -s h -l help -d 'Show help'");
    expect(script).toContain("complete -c test-cli -s V -l version -d 'Show version'");
    expect(script).toContain("-l verbose");
    expect(script).toContain("-l config");
  });

  test("includes commands with descriptions", () => {
    expect(script).toContain("-a build -d 'Build the project'");
    expect(script).toContain("-a serve -d 'Start development server'");
    expect(script).toContain("-a config -d 'Manage configuration'");
  });

  test("excludes hidden commands", () => {
    expect(script).not.toContain("-a internal");
  });

  test("includes command-specific options", () => {
    expect(script).toContain("# build options");
    expect(script).toContain("-l output");
    expect(script).toContain("-l watch");
    expect(script).toContain("# serve options");
    expect(script).toContain("-l port");
  });

  test("handles subcommands", () => {
    expect(script).toContain("# config subcommands");
    expect(script).toContain("-a get -d 'Get config value'");
    expect(script).toContain("-a set -d 'Set config value'");
  });

  test("marks options requiring arguments", () => {
    // Options with type !== boolean should have -r flag
    expect(script).toContain("-l output");
    expect(script.match(/-l output.*-r/s) || script.match(/-r.*-l output/s)).toBeTruthy();
  });
});

describe("generateCompletion", () => {
  const config = createTestConfig();

  test("generates bash completion", () => {
    const script = generateCompletion(config, "bash");
    expect(script).toContain("#!/usr/bin/env bash");
    expect(script).toContain("complete -F");
  });

  test("generates zsh completion", () => {
    const script = generateCompletion(config, "zsh");
    expect(script).toContain("#compdef");
    expect(script).toContain("_arguments");
  });

  test("generates fish completion", () => {
    const script = generateCompletion(config, "fish");
    expect(script).toContain("complete -c");
    expect(script).toContain("commandline");
  });

  test("throws for unsupported shell", () => {
    expect(() => generateCompletion(config, "powershell" as any)).toThrow("Unsupported shell");
  });
});

describe("edge cases", () => {
  test("handles CLI with no commands", () => {
    const config: CliConfig = {
      name: "empty-cli",
      version: "1.0.0",
      description: "Empty CLI",
      commands: {},
      globalOptions: [
        {
          name: "help",
          short: "h",
          description: "Show help",
          type: "boolean",
          required: false,
          default: false,
        },
      ],
    };

    const bash = generateBashCompletion(config);
    expect(bash).toContain("_empty_cli_completion");

    const zsh = generateZshCompletion(config);
    expect(zsh).toContain("_empty_cli");

    const fish = generateFishCompletion(config);
    expect(fish).toContain("complete -c empty-cli");
  });

  test("handles CLI name with hyphens", () => {
    const config: CliConfig = {
      name: "my-awesome-cli",
      version: "1.0.0",
      description: "CLI with hyphens",
      commands: {},
      globalOptions: [],
    };

    const bash = generateBashCompletion(config);
    expect(bash).toContain("_my_awesome_cli_completion");

    const zsh = generateZshCompletion(config);
    expect(zsh).toContain("_my_awesome_cli");

    const fish = generateFishCompletion(config);
    expect(fish).toContain("__my_awesome_cli_needs_command");
  });

  test("handles option descriptions with special characters", () => {
    const config: CliConfig = {
      name: "special-cli",
      version: "1.0.0",
      description: "Special CLI",
      commands: {},
      globalOptions: [
        {
          name: "query",
          short: "q",
          description: "Search query (e.g. 'foo [bar]')",
          type: "string",
          required: false,
        },
      ],
    };

    // Should not throw
    expect(() => generateBashCompletion(config)).not.toThrow();
    expect(() => generateZshCompletion(config)).not.toThrow();
    expect(() => generateFishCompletion(config)).not.toThrow();
  });

  test("handles commands with only hidden subcommands", () => {
    const hiddenSub: CommandConfig = {
      name: "secret",
      description: "Hidden subcommand",
      aliases: [],
      arguments: [],
      options: [],
      subcommands: {},
      hidden: true,
    };

    const parentCmd: CommandConfig = {
      name: "parent",
      description: "Parent command",
      aliases: [],
      arguments: [],
      options: [],
      subcommands: {
        secret: hiddenSub,
      },
      hidden: false,
    };

    const config: CliConfig = {
      name: "test",
      version: "1.0.0",
      description: "Test",
      commands: {
        parent: parentCmd,
      },
      globalOptions: [],
    };

    const bash = generateBashCompletion(config);
    expect(bash).not.toContain("secret");

    const zsh = generateZshCompletion(config);
    expect(zsh).not.toContain("secret");

    const fish = generateFishCompletion(config);
    expect(fish).not.toContain("secret");
  });
});
