/**
 * Bash completion script generator
 */

import type { CliConfig, CommandConfig, OptionDef } from "../types.ts";

/**
 * Generate bash completion script for a CLI
 */
export function generateBashCompletion(config: CliConfig): string {
  const name = config.name;
  const funcName = `_${name.replace(/-/g, "_")}_completion`;

  const lines: string[] = [
    "#!/usr/bin/env bash",
    "",
    `# Bash completion for ${name}`,
    `# Generated by boune`,
    "",
    `${funcName}() {`,
    `    local cur="\${COMP_WORDS[COMP_CWORD]}"`,
    `    local prev="\${COMP_WORDS[COMP_CWORD-1]}"`,
    "",
    "    # Find the command (first non-option argument)",
    "    local cmd_idx=1",
    '    local cmd=""',
    '    local subcmd=""',
    "    while [[ $cmd_idx -lt $COMP_CWORD ]]; do",
    `        local word="\${COMP_WORDS[cmd_idx]}"`,
    `        if [[ "$word" != -* ]]; then`,
    `            if [[ -z "$cmd" ]]; then`,
    `                cmd="$word"`,
    "            else",
    `                subcmd="$word"`,
    "                break",
    "            fi",
    "        fi",
    "        ((cmd_idx++))",
    "    done",
    "",
  ];

  // Generate global options
  const globalOpts = config.globalOptions
    .filter((o) => !["help", "version"].includes(o.name))
    .map((o) => formatBashOption(o))
    .join(" ");

  const defaultGlobalOpts = "--help --version" + (globalOpts ? " " + globalOpts : "");

  // Get visible commands
  const commands = getVisibleCommands(config.commands);
  const commandNames = commands.map((c) => c.name).join(" ");

  // Generate command cases
  lines.push(`    case "$cmd" in`);

  for (const command of commands) {
    lines.push(...generateBashCommandCase(command, "        "));
  }

  // Default case (root level)
  lines.push("        *)");
  lines.push(`            if [[ "$cur" == -* ]]; then`);
  lines.push(`                COMPREPLY=($(compgen -W "${defaultGlobalOpts}" -- "$cur"))`);
  lines.push("            else");
  lines.push(`                COMPREPLY=($(compgen -W "${commandNames}" -- "$cur"))`);
  lines.push("            fi");
  lines.push("            ;;");
  lines.push("    esac");
  lines.push("}");
  lines.push("");
  lines.push(`complete -F ${funcName} ${name}`);
  lines.push("");

  return lines.join("\n");
}

function formatBashOption(option: OptionDef): string {
  const parts: string[] = [];
  if (option.short) parts.push(`-${option.short}`);
  const longFlag = option.long ?? option.name;
  parts.push(`--${longFlag}`);
  return parts.join(" ");
}

function getVisibleCommands(commands: Record<string, CommandConfig>): CommandConfig[] {
  const seen = new Set<CommandConfig>();
  const result: CommandConfig[] = [];

  for (const config of Object.values(commands)) {
    if (!seen.has(config) && !config.hidden) {
      seen.add(config);
      result.push(config);
    }
  }

  return result;
}

function generateBashCommandCase(command: CommandConfig, indent: string): string[] {
  const lines: string[] = [];
  const opts = command.options.map((o) => formatBashOption(o)).join(" ");
  const allOpts = opts ? `--help ${opts}` : "--help";

  // Get subcommands
  const subcommands = getVisibleCommands(command.subcommands);
  const subcommandNames = subcommands.map((s) => s.name).join(" ");

  lines.push(`${indent}"${command.name}")`);

  if (subcommands.length > 0) {
    // Handle subcommand completion
    lines.push(`${indent}    case "$subcmd" in`);

    for (const sub of subcommands) {
      const subOpts = sub.options.map((o) => formatBashOption(o)).join(" ");
      const subAllOpts = subOpts ? `--help ${subOpts}` : "--help";

      lines.push(`${indent}        "${sub.name}")`);
      lines.push(`${indent}            if [[ "$cur" == -* ]]; then`);
      lines.push(`${indent}                COMPREPLY=($(compgen -W "${subAllOpts}" -- "$cur"))`);
      lines.push(`${indent}            fi`);
      lines.push(`${indent}            ;;`);
    }

    lines.push(`${indent}        *)`);
    lines.push(`${indent}            if [[ "$cur" == -* ]]; then`);
    lines.push(`${indent}                COMPREPLY=($(compgen -W "${allOpts}" -- "$cur"))`);
    lines.push(`${indent}            else`);
    lines.push(`${indent}                COMPREPLY=($(compgen -W "${subcommandNames}" -- "$cur"))`);
    lines.push(`${indent}            fi`);
    lines.push(`${indent}            ;;`);
    lines.push(`${indent}    esac`);
  } else {
    lines.push(`${indent}    if [[ "$cur" == -* ]]; then`);
    lines.push(`${indent}        COMPREPLY=($(compgen -W "${allOpts}" -- "$cur"))`);
    lines.push(`${indent}    fi`);
  }

  lines.push(`${indent}    ;;`);

  return lines;
}
