import type { CliConfig, CommandConfig, InternalOptionDef } from "../types/index.ts";

/**
 * Generate fish completion script for a CLI
 */
export function generateFishCompletion(config: CliConfig): string {
  const name = config.name;

  const lines: string[] = [
    `# Fish completion for ${name}`,
    `# Generated by boune`,
    "",
    `# Disable file completion by default`,
    `complete -c ${name} -f`,
    "",
  ];

  // Get visible commands
  const commands = getVisibleCommands(config.commands);
  const _commandNames = commands.map((c) => c.name);

  // Helper function to check if we're at a specific command
  lines.push(`# Helper function to check current command context`);
  lines.push(`function __${name.replace(/-/g, "_")}_needs_command`);
  lines.push(`    set -l cmd (commandline -opc)`);
  lines.push(`    if test (count $cmd) -eq 1`);
  lines.push(`        return 0`);
  lines.push(`    end`);
  lines.push(`    return 1`);
  lines.push(`end`);
  lines.push("");

  // Helper to check if we're in a specific command
  lines.push(`function __${name.replace(/-/g, "_")}_using_command`);
  lines.push(`    set -l cmd (commandline -opc)`);
  lines.push(`    if test (count $cmd) -gt 1`);
  lines.push(`        if test $argv[1] = $cmd[2]`);
  lines.push(`            return 0`);
  lines.push(`        end`);
  lines.push(`    end`);
  lines.push(`    return 1`);
  lines.push(`end`);
  lines.push("");

  // Global options
  lines.push("# Global options");
  lines.push(`complete -c ${name} -s h -l help -d 'Show help'`);
  if (config.version) {
    lines.push(`complete -c ${name} -s V -l version -d 'Show version'`);
  }

  for (const option of config.globalOptions) {
    if (["help", "version"].includes(option.name)) continue;
    lines.push(formatFishOption(name, option));
  }
  lines.push("");

  // Commands
  if (commands.length > 0) {
    lines.push("# Commands");
    for (const cmd of commands) {
      const desc = cmd.description.replace(/'/g, "\\'");
      lines.push(
        `complete -c ${name} -n __${name.replace(/-/g, "_")}_needs_command -a ${cmd.name} -d '${desc}'`,
      );
    }
    lines.push("");

    // Command-specific options
    for (const cmd of commands) {
      lines.push(...generateFishCommandCompletions(name, cmd));
    }
  }

  return lines.join("\n");
}

function formatFishOption(cliName: string, option: InternalOptionDef, condition?: string): string {
  const parts = [`complete -c ${cliName}`];

  if (condition) {
    parts.push(`-n "${condition}"`);
  }

  if (option.short) {
    parts.push(`-s ${option.short}`);
  }

  const longFlag = option.long ?? option.name;
  parts.push(`-l ${longFlag}`);

  if (option.type !== "boolean") {
    parts.push("-r"); // requires argument
  }

  const desc = (option.description || "").replace(/'/g, "\\'");
  parts.push(`-d '${desc}'`);

  return parts.join(" ");
}

function getVisibleCommands(commands: Record<string, CommandConfig>): CommandConfig[] {
  const seen = new Set<CommandConfig>();
  const result: CommandConfig[] = [];

  for (const config of Object.values(commands)) {
    if (!seen.has(config) && !config.hidden) {
      seen.add(config);
      result.push(config);
    }
  }

  return result;
}

function generateFishCommandCompletions(cliName: string, command: CommandConfig): string[] {
  const lines: string[] = [];
  const funcName = cliName.replace(/-/g, "_");
  const condition = `__${funcName}_using_command ${command.name}`;

  lines.push(`# ${command.name} options`);

  // Add --help for the command
  lines.push(`complete -c ${cliName} -n "${condition}" -l help -d 'Show help'`);

  // Command-specific options
  for (const option of command.options) {
    lines.push(formatFishOption(cliName, option, condition));
  }

  // Handle subcommands
  const subcommands = getVisibleCommands(command.subcommands);
  if (subcommands.length > 0) {
    lines.push("");
    lines.push(`# ${command.name} subcommands`);

    for (const sub of subcommands) {
      const desc = sub.description.replace(/'/g, "\\'");
      lines.push(`complete -c ${cliName} -n "${condition}" -a ${sub.name} -d '${desc}'`);
    }

    // Subcommand options
    for (const sub of subcommands) {
      const subCondition = `__${funcName}_using_command ${command.name}; and contains ${sub.name} (commandline -opc)`;
      lines.push("");
      lines.push(`# ${command.name} ${sub.name} options`);
      lines.push(`complete -c ${cliName} -n "${subCondition}" -l help -d 'Show help'`);

      for (const option of sub.options) {
        lines.push(formatFishOption(cliName, option, subCondition));
      }
    }
  }

  lines.push("");
  return lines;
}
